### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by tylerdq** [brettchalupa/sokoworld#42]
I'm trying to get sokoworld running on my installation of KISS Linux (a distribution that uses Wayland for desktop sessions). It compiles fine with `cargo build --release` but when I try to run the game I get this error:

```
thread 'main' panicked at /home/tyler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/miniquad-0.4.5/src/lib.rs:346:50:
X11 backend failed: LibraryNotFound(DlOpenError("libX11.so.6"))
```

It looks like an X11 Linux desktop is assumed. Is it possible to compile sokoworld with support for wayland backend?

**Comment by tylerdq** [comment]
Oh awesome, I'm glad there's a path forward because this game is great and I'd love to run it locally! Looking forward to the next release.

**Comment by brettchalupa** [comment]
Should be fixed in this commit https://github.com/brettchalupa/sokoworld/pull/41/commits/768ad9993dad50ef3eeae98f10a8fa1b8a741072 and will go out with the v0.3 release, which I can build and release this evening. 🚢

**Comment by tylerdq** [comment]
Nice, looks like it solved the X11 issue for me. I'm now having a different issue referenced in #43
